SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE Accounts RESTART IDENTITY;
TRUNCATE TABLE Groups RESTART IDENTITY;
TRUNCATE TABLE Relationship RESTART IDENTITY;
TRUNCATE TABLE Members RESTART IDENTITY;
TRUNCATE TABLE Phones RESTART IDENTITY;
TRUNCATE TABLE Requests RESTART IDENTITY;
SET REFERENTIAL_INTEGRITY TRUE;
